// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caycrcdpaklikxnihinm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNheWNyY2RwYWtsaWt4bmloaW5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MjkzMjEsImV4cCI6MjA3NDUwNTMyMX0.1jBRs3utnbO2hBdcf5o6VZ83KSEvIqkQ1rWNDRwfh_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});